image: node:latest

stages:
  # List of stages for jobs, and their order of execution
  - build
  - deploy
build-job:
  # This job runs in the build stage, which runs first.
  stage: build
  script:
    - apt-get -qq update
    - apt-get install -y jq
    - which jq
    - command -v jq
  extends: .git:push

.git:push:
  before_script:
    # Clone the repository via HTTPS inside a new directory
    - git clone "https://${GITLAB_USERNAME}:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" "${CI_COMMIT_SHA}"

    # Set the displayed user with the commits that are about to be made
    - git config --global user.email "${GIT_USER_EMAIL:-$GITLAB_USER_EMAIL}"
    - git config --global user.name "${GIT_USER_NAME:-$GITLAB_USER_NAME}"
  after_script:
    # cd into the new cleanly created repo for pushing purposes
    - cd "${CI_COMMIT_SHA}"
    - ls -al
    # - echo "Compiling the code..."; bash ./ci.bash && echo "Compile complete."
    - |-
      wget -qO- 'https://raw.githubusercontent.com/SF-XIV/dalamud-plugins/main/repo.json' > sfxiv.tmp
      wget -qO- 'https://raw.githubusercontent.com/LeonBlade/DalamudPlugins/main/repo.json' > leonblade.tmp
      wget -qO- 'https://raw.githubusercontent.com/Aida-Enna/XIVPlugins/main/repo.json' > aidaenna.tmp
      wget -qO- 'https://raw.githubusercontent.com/NightmareXIV/MyDalamudPlugins/main/pluginmaster.json' > nightmarexiv.tmp
      wget -qO- 'https://raw.githubusercontent.com/arcticnw/DalamudPlugins/main/repo.json' > actucnw.tmp
    - |- 
      for file in ./*.tmp; do
        cat $file | jq -s 'flatten(1)' jq -s > new_repo.json
      done
    - echo "Checking for differences"; diff repo.json new_repo.json
    - echo "overwriting repo JSON with new file"
    - mv -v new_repo.json repo.json
    - rm -v tmp*.json
    - ls -al
    # Add all generated files to Git
    - git add .
    - |-
      # Check if we have modifications to commit
      CHANGES=$(git status --porcelain | wc -l)

      if [ "$CHANGES" -gt "0" ]; then
        # Show the status of files that are about to be created, updated or deleted
        git status

        # Commit all changes
        git commit -m "Automated update"

        # Update the repository and make sure to skip the pipeline create for this commit
        git push origin "${CI_DEFAULT_BRANCH}" -o ci.skip
      fi
