name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GIT_STRATEGY: clone

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xenhat/dalamud-repo-image:latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      -
        name: Trust all folders
        run: git config --global --add safe.directory '*'
      -
        name: Run merge script
        run: bash merge_repos.bash
        shell: bash
      -
        name: Create local changes
        id: check_changes
        run: git add .
#      -
#        name: Commit and push changes
#        uses: actions-js/push@master
#        with:
#          github_token: ${{ secrets.REPO_PUSH_TOKEN }}
